declare const styles: {
  readonly title: string
  readonly titleAmber: string
  readonly titleStpToken: string
  readonly form: string
  readonly signupForm: string
  readonly inputGroup: string
  readonly label: string
  readonly input: string
  readonly inputPhone: string
  readonly textarea: string
  readonly inputIcon: string
  readonly inputIconButton: string
  readonly inputPhoneButton: string
  readonly checkboxDiv: string
  readonly checkboxInput: string
  readonly checkboxLabel: string
  readonly checkboxLink: string
  readonly forgotLabel: string
  readonly forgotLink: string
  readonly termsLink: string
  readonly column: string
  readonly separator: string
  readonly columnSeparator: string
  readonly hint: string
  readonly hintList: string
  readonly hintIcon: string
  readonly hintItem: string
  readonly remembermeGroup: string
  readonly forgotGroup: string
  readonly signupLinkLabel: string
  readonly signup: string
  readonly signupLink: string
  readonly buttonLogin: string
  readonly buttonReset: string
  readonly messages: string
  readonly message: string
  readonly updatesLabel: string
  readonly social: string
}
export = styles
