declare const styles: {
  readonly section: string
  readonly infoBackground: string
  readonly content: string
  readonly question: string
  readonly form: string
  readonly box: string
  readonly lastBox: string
  readonly label: string
  readonly labelText: string
  readonly input: string
  readonly inputPhone: string
  readonly inputPhoneButton: string
  readonly textarea: string
  readonly labelCheckbox: string
  readonly checkbox: string
  readonly checkboxText: string
  readonly button: string
  readonly message: string
  readonly linkMailto: string
  readonly inputPhoneContainer: string
  readonly loading: string
  readonly messages: string
  readonly selectDiv: string
  readonly select: string
  readonly selectValue: string
  readonly selectButton: string
  readonly selectArrow: string
  readonly selectList: string
  readonly selectOption: string
}
export = styles
